travis:
  secure:
    BINSTAR_TOKEN: N03Zhej0uL/V0tX8qhFuhBe4q9N0kltua6RCwkAr+SaDqujbPuPxudviQixqny8Xa94VgkYkytcow1KQ94mBrE8PnRvWQ5Fm9/3Vq/Q1rRcpztG4oh1/dk1y2Xa9K7mMxTZ+kjq+8wAZPnosVFY6+aDLLkECDrALiJyAIg2jKZChbksH6+N7x+ZZ21cNmaNpyRJTutiWA686xC75gdiwGCkog5axAS05slUHMOXVbdq+e5GZ4Het09qp4rKpVqS6b+crnLxv0ZkD6dm1ONwkQ26dl7HI2ftyHzqqJbHIsQUgJTkIBF7ga2TsYpVp//mAocTubxQpMiU8B/oSsm+G0p1SmQ2QfZoj42+B2rR/pAKhrAwq80frbOYveGyM3mR5srvpgH4PrXlkUJUeULJ8hcN1Usi2BpOtMEiSaHy2x96W0WThbpeggR6iyb2QDElRgeGzXV8wrHbAmTIBJRBVV34qH0eW7/3voVyJYKm2tc9uohExvse9cBFzxNxGvDNYZW+AifmlUBYbKeaAuRzmC6i7+niUwAYoqqy5NGbM4l+NPkNT6IlIFlxIFFX94QtR/zPE2toiDvxFU4q0ap6slsxdo6s0e8GP76rr7gAwhKdz32g/wxN8A9HeRkIX/Pa8d4ogfYR4vzZdbwvWD74Bi6hMSEj6LUM9L8wExqg88+4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
